apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: ecm
spec:
  type: ClusterIP
  ports:
    - port: 2049
      name: nfs
      protocol: TCP
      targetPort: 2049
    - port: 111
      name: portmapper
      targetPort: 111
      protocol: UDP
    - port: 20048
      name: mountd
      targetPort: 20048
  selector:
    app: nfs-server
