apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared
  namespace: ecm
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 1Ti
  storageClassName: ecm-shared
