apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "infinity"]
    volumeMounts:
        - mountPath: /exports
          name: pvc-ecm-global-2
          readOnly: false

volumes:
  - name: pvc-ecm-global-2
    persistentVolumeClaim:
      claimName: pvc-ecm-global-2
